export { GlobalSearchBar } from './GlobalSearchBar';
export { SearchHistoryPanel } from './SearchHistoryPanel';
export { AreaRestritaHeader } from './AreaRestritaHeader';
export { MobileBottomNav } from './MobileBottomNav';
export { default as RecentActivity } from './RecentActivity';
export { WelcomeBanner } from './WelcomeBanner';
export { DashboardHero } from './DashboardHero';
export { QuickAccessBar } from './QuickAccessBar';
export { DashboardCourseCard } from './DashboardCourseCard';
export { KnowledgeBaseSection } from './KnowledgeBaseSection';
export { HeroPlanejamento } from './HeroPlanejamento';
export { AreaRestritaMenuTrigger } from './AreaRestritaMenuTrigger';
export { AreaRestritaMenuDrawer } from './AreaRestritaMenuDrawer';
